services:
  - type: web
    name: rails-api
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: rails-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DEVISE_JWT_SECRET_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET
        sync: false
      - key: R2_ENDPOINT
        sync: false

databases:
  - name: rails-db
    databaseName: rails_production
    plan: free
